### ISSUE TITLE
t/connection.t fails - strange behaviour

### ISSUE THREAD

**Issue by akarelas** [jhthorsen/mojo-redis#25] opened 2018-12-11 03:12 UTC
_Note: My redis server (v5.0.2) is on a different machine than the one running the test, but that was no problem for almost all of the other tests._

I get this error when running `TEST_ONLINE=redis://10.11.12.13 carton exec -- prove -vl t/connection.t`

```
ok 20 - new fork gets a new connecion
# New connection, because URL changed
ok 21 - database was not enqued
Mojo::Reactor::Poll: I/O watcher failed: Mojo::Redis::Connection: Connection refused at /home/appuser/work/mojo-redis/local/lib/perl5/Mojo/EventEmitter.pm line 19.
not ok 22 - connected
#   Failed test 'connected'
#   at t/connection.t line 112.
not ok 23 - connection was closed on destruction
#   Failed test 'connection was closed on destruction'
#   at t/connection.t line 117.
1..23
# Looks like you failed 2 tests of 23.
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/23 subtests 
```

**HOWEVER:** When I ALSO install Redis 4.0.9 on the machine that's running the test, and run the exact same command (even with TEST_ONLINE pointing to the other, remote, 5.0.2, Redis server), the same test succeeds without errors. So, it seems the test connects to the local Redis at some point. Which **might** be a little strange (I don't know), since the string Mojo::Redis->new in that file doesn't appear anywhere without TEST_ONLINE in it.

Indeed:
`systemctl start redis` on the local machine... the test succeeds
`systemctl stop redis` on the local machine... the test fails where I told you

**Comment by jhthorsen** [comment] 2018-12-11 04:46
Thanks for reporting in 👍

The problem is the changing of "host". This should be fixed in ca674140b6fc63c8e148445fcfd1e94678572c07

**Closed** 2018-12-11 04:46 UTC
Labels: bug
