### ISSUE TITLE
Add notify_p and change the API for notify()

### ISSUE THREAD

**Issue by shadowcat-mst** [jhthorsen/mojo-redis#47] opened 2019-06-02 19:58 UTC
Currently:

    sub notify {
      my ($self, $name, $payload) = @_;
      $payload = to_json $payload if $self->{json}{$name};
      shift->db->call_p(PUBLISH => $name, $payload);
    }

I think to make it make sense:

    sub notify_p {
      my ($self, $name, $payload) = @_;
      $payload = to_json $payload if $self->{json}{$name};
      shift->db->call_p(PUBLISH => $name, $payload);
    }
    sub notify { shift->notify_p(@_)->wait }

so now

    $redis->notify(...);

still works even in a blocking scenario (where there's no running ioloop, e.g. in a minion task)

**Comment by jhthorsen** [comment] 2019-06-04 13:54
Sounds like a good idea! I'll fix this as soon as I free up some time, but I also welcome a PR.

**Comment by jhthorsen** [comment] 2020-04-24 04:29
I started on https://github.com/jhthorsen/mojo-redis/compare/jhthorsen/notify_p, but it seem to be leaking for some reason... Or maybe the test case is wrong. Will hopefully figure this out in #52.

**Comment by mohawk2** [comment] 2020-05-10 15:48
The leak was because `db->call_p` was keeping a strong reference to the db for some reason. That is changed (and since all the tests pass after stopping that, hopefully fixed!) in #54. If that is merged, it will mean your `notify_p` code can be rebased past my `ci-fix` commits and merged. I have in fact done this on my fork's `mohawk2/notify_p`, visible at https://github.com/mohawk2/mojo-redis/compare/ci-fix...mohawk2:mohawk2/notify_p, where I have also resolved the conflict caused by my adding a bit more memory-cycle testing to `t/pubsub.t`.

**Comment by jhthorsen** [comment] 2020-10-02 01:23
This is implemented in v3.25.

**Closed** 2020-10-02 01:24 UTC
Labels: enhancement
